### ISSUE TITLE
Permission denied to access property "getSelection" on cross-origin object

### ISSUE THREAD

**Issue by mc4bbs** [SalvatoreMeschini/CheckThemAll#1]
I am seeing the error: Permission denied to access property "getSelection" on cross-origin object.

Please advise work-around.

**Comment by nandaccio** [comment]
You can read more about it here: https://en.wikipedia.org/wiki/Cross-site_scripting

Cross-site content can NOT be read/modified by JavaScript for security reasons, if you have access to the site that is loaded into the iframe you might want to edit the CORS headers (Access-Control-Allow-Origin).

In this case the add-on is simply reporting that the content can't be read because of the XSS protection.

**Comment by SalvatoreMeschini** [comment]
Nandaccio is right, CheckThemAll can't access such content because of XSS protection. You might want to disable that kind of notifications (see Options page), but in any case the add-on can't check/uncheck those checkboxes because they are made available through an "external iframe".

Since there is no workaround, aside from some specific cases, it's something that can't be fixed.
See the "Notes" section: https://github.com/SalvatoreMeschini/CheckThemAll/blob/master/README.md
